### ISSUE TITLE
conda forge

### ISSUE THREAD

**Issue by AaronDavidSchneider** [pcubillos/bibmanager#82]
Hi,

since some people prefer conda over pip, what do you think about packaging it for anaconda?
Packaging a pypi project for anaconda is actually quite simple and well explained: https://github.com/conda-forge/staged-recipes.
The conda forge bot will even automatically update the recipe once there is a new version on pypi.

**Comment by AaronDavidSchneider** [comment]
This is a recipe that I just created with grayskull:
```yaml
{% set name = "bibmanager" %}
{% set version = "1.3.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/bibmanager-{{ version }}.tar.gz
  sha256: cc3f31fa5827cfcb8a57def8334b6b7aa7cfb4d4836fc24afa36094172f23f06

build:
  number: 0
  noarch: python
  entry_points:
    - bibm = bibmanager.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - numpy >=1.15.1
    - packaging >=17.1
    - prompt-toolkit >=3.0.5
    - pygments >=2.2.0
    - python
    - requests >=2.19.1

test:
  imports:
    - bibmanager
    - bibmanager.ads_manager
  commands:
    - pip check
    - bibm --help
  requires:
    - pip

about:
  home: https://github.com/pcubillos/bibmanager
  summary: A BibTeX manager for LaTeX projects
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pcubillos
```
